feat: 인증화면 스타일링 추가, 모달창 구현, 등록 폼 로직 초안
diary-dog/meong-side-FE pull request #27
Opened 2024-03-30 21:15 UTC by sungyuha

### 관련 문서

인증화면 스타일링 추가, 모달창 구현 완료되었습니다.

Closes [issue link]

### 변경사항:

등록 폼 로직 개발하고 있습니다.

### 확인할 목록:

등록 폼 로직 개발중입니다. 아이콘 import 오류 있습니다.

2024-03-30 21:56 UTC, j2h30728 requested changes
공통적으로 적용되는 사항이 무척 많습니다.
이전에 html button 태그의 color 프로퍼티에 대해서 말씀드렸을 때, 이해하신줄 알았었는데 코드상에 너무 많습니다.
또한, 이전에 말씀드린것 과 같이 동작하는 코드만 풀리퀘스트 요청 부탁드립니다.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/UploadBath.styled.ts
> +  // gap: 38px;
주석 확인 부탁드립니다.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/UploadBath.styled.ts
> +
스타일드 컴포넌트에서 props로 넘겨주게되면 타입을 명시해주지않으면 에러가 나는 것으로 알고 있습니다 .$active를 가져올 때 타입 에러가 나지않나요?
[스타일드 컴포넌트 공식문서 : props](https://styled-components.com/docs/basics#adapting-based-on-props)

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/UploadBath.tsx
> +    setShowModal(true);
baseUrl 이 없는 상태인데 해당 로직은 동작하나요? 확인부탁드립니다.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/UploadBath.tsx
> +          </button>
html button 태그에는 color 프로퍼티가 존재하지 않습니다.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/UploadMeal.tsx
> +  const [selectedSnack, setSelectedSnack] = useState('');
현재 식사(meal) 로직이 있어야하는 코드인데 간식(treats)로 확인되는 식별자가 보입니다. 확인 부탁드립니다.

그리고 간식 식별자명은 snack이 아닌 것으로 알고있습니다. 저희 팀 피그잼 확인해주세요.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/VerificationBath.tsx
Verification 페이지들은 어느 ROUTE_PATH로 라우팅되나요? 
현재 router 파일이 수정되지 않았기 때문에  VERIFICATIONWALK 파일을 제외하고는 전부 라우팅이 안될 것 같아 보입니다.

2024-03-30 21:56 UTC, j2h30728 commented on src/pages/verification/VerificationMeal.tsx
> +      navigate('/verification/Mealpost'); // 리디렉션할 경로
uri로 들어가는 route  path는 대체로 소문자를 사용합니다.
또한 이미 셋팅해두신 route path와 다릅니다.

2024-03-30 22:04 UTC, sungyuha commented on src/pages/verification/VerificationBath.tsx
라우팅은 아까전부터 충돌 이슈가 생겨서 import 하지 않았습니다.

2024-03-30 22:18 UTC, sungyuha commented on src/pages/verification/UploadBath.styled.ts
> +  // gap: 38px;
확인하겠습니다. 감사헤요

2024-03-30 22:19 UTC, sungyuha commented on src/pages/verification/UploadBath.styled.ts
> +
감사합니다!

2024-03-30 22:19 UTC, sungyuha commented on src/pages/verification/UploadBath.tsx
> +    setShowModal(true);
확인하겠습니다.

2024-03-30 22:19 UTC, sungyuha commented on src/pages/verification/UploadMeal.tsx
> +  const [selectedSnack, setSelectedSnack] = useState('');
감사해요! 확인하겠습니다.

2024-03-30 22:20 UTC, sungyuha commented on src/pages/verification/VerificationMeal.tsx
> +      navigate('/verification/Mealpost'); // 리디렉션할 경로
수정하겠습니다.

2024-03-30 22:21 UTC, sungyuha commented on src/pages/verification/UploadBath.tsx
> +          </button>
수정하겠습니다.

2024-03-30 22:30 UTC, j2h30728 commented on src/pages/verification/VerificationBath.tsx
그럼 라우팅되지 않는 페이지를 생성하신것과 같은데 이것을 의도하고 생성하신건가요?

2024-03-31 00:42 UTC, sungyuha commented on src/pages/verification/VerificationBath.tsx
충돌이 안생기게 추후에 업데이트 하려고 했어요

2024-04-06 04:50 UTC, closed without merging