feat: ui화면 설계 및 스타일링, 라우팅 연결결x [#7]
diary-dog/meong-side-FE pull request #8
Opened 2024-03-27 06:08 UTC by sungyuha

### 관련 문서

Closes [issue link]

### 변경사항:

### 확인할 목록:

2024-03-27 13:41 UTC, sungyuha commented
main.tsx 파일 수정했습니다.

2024-03-27 13:42 UTC, sungyuha commented
main.tsx 파일 수정 완료했습니다.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Upload.tsx
> +        <NavLink key={imgUploadpage} to="verification/$:type/upload" />;
map 메서드의 콜백함수내에서 return 문을 사용하지않으면 컴포넌트가 렌더되지않습니다.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Upload.tsx
> +`;
풀리퀘스트 오픈시에 주석처리한 코드는 제거해주세요.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/UploadBath.tsx
> +      })}
map 메서드 콜백함수내에 return 문 확인 부탁드립니다.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Upload.tsx
>    const { type } = useParams();
인증 타입마다 페이지를 만드려고 하신다면 동적라우팅에 관한 코드는 제거 부탁드립니다.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Upload.tsx
> +          <button onClick={() => navigator(ROUTE_PATH.HOME)} color="primary">
기본 button 태그에는 color 프로퍼티 는 존재하지 않습니다. 확인부탁드려요.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Upload.tsx
> +      background: #d9d9d9 url() center center no-repeat;
url 에는 빈값이 들어가고있습니다. 확인 부탁드려요.

2024-03-27 14:56 UTC, j2h30728 commented on src/pages/verification/Verification.tsx
> +const PWrapper = styled.div`
식별자명을 명명할 때에는 줄임말 보다는 풀네임으로 쓰시는것을 권장드립니다.

2024-03-27 15:01 UTC, j2h30728 commented on src/pages/verification/UploadMeal.tsx
> +`;
중복되는 styled components 코드들은 upload.styled.ts 와 같이 파일을 따로 빼서, 사용하는 곳에서 import 하는 방식으로 구현 하는 것은 어떨까요?

2024-03-28 01:56 UTC, sungyuha commented on src/pages/verification/UploadMeal.tsx
> +`;
중복되는 styled components 코드들은 upload.styled.ts 와 같이 파일을 따로 빼서 사용하려고 했는데 에러가 발생해서 이 부분만 제외 했으니 참고 부탁드립니다.

2024-03-28 02:08 UTC, j2h30728 requested changes

2024-03-28 02:08 UTC, j2h30728 commented on src/router/constants.ts
> +  VERIFICATION_UPLOADETC: "verification/:type/UploadEtc",
동적라우팅을 하시는게 아니라면 path parameter는 쓰지않습니다. 확인 부탁드려요.

react router의 path parameter을 검색해보시길 부탁드립니다.

2024-03-28 02:08 UTC, j2h30728 commented on src/pages/index.ts
> +export { default as Slides } from "./Slide";
export { default as Slide } from "./Slide"; 입니다. 확인부탁드려요

2024-03-28 02:08 UTC, j2h30728 commented on src/pages/verification/UploadBath.tsx
> +`;
주석이 아직도 존재합니다.

2024-03-28 02:38 UTC, sungyuha commented on src/router/constants.ts
> +  VERIFICATION_UPLOADETC: "verification/:type/UploadEtc",
알려주셔서 고마워요! 검색해보고 수정하겠습니다.

2024-03-28 02:39 UTC, sungyuha commented on src/pages/index.ts
> +export { default as Slides } from "./Slide";
감사합니다.

2024-03-28 02:39 UTC, sungyuha commented on src/pages/verification/UploadBath.tsx
> +`;
삭제했습니다.

2024-03-28 02:40 UTC, sungyuha commented on src/pages/verification/Upload.tsx
> +        <NavLink key={imgUploadpage} to="verification/$:type/upload" />;
삭제했습니다. 
알려주셔서 고맙습니다.

2024-03-28 02:40 UTC, sungyuha commented on src/pages/verification/Upload.tsx
> +`;
삭제했습니다.
알려주셔서 고맙습니다.

2024-03-28 02:40 UTC, sungyuha commented on src/pages/verification/UploadBath.tsx
> +      })}
확인해서 삭제 완료했습니다.

2024-03-28 02:41 UTC, sungyuha commented on src/pages/verification/Upload.tsx
>    const { type } = useParams();
확인 후 삭제 완료했습니다.

2024-03-28 02:41 UTC, sungyuha commented on src/pages/verification/Upload.tsx
> +      background: #d9d9d9 url() center center no-repeat;
확인 후 삭제 완료했습니다.

2024-03-28 02:42 UTC, sungyuha commented on src/pages/verification/Verification.tsx
> +const PWrapper = styled.div`
고맙습니다! 수정 완료했습니다.

2024-03-28 02:55 UTC, sungyuha commented
깃허브에서 resolve confilts를 눌러 해결했는데 확인해주세요.

2024-03-28 04:47 UTC, j2h30728 requested changes

2024-03-28 04:47 UTC, j2h30728 commented on src/pages/verification/Modal.tsx
Modal 은 페이지가 아닌것을 보이는데 페이지 컴포넌트와 그냥 컴포넌트는 폴더로 구분하는게 좋지않을까요?

2024-03-28 04:47 UTC, j2h30728 commented on src/pages/verification/UploadBath.tsx
> +`;
주석이 삭제 되지 않았습니다.

2024-03-28 04:47 UTC, j2h30728 commented on src/router/index.tsx
> +      },
최종 풀리퀘 요청 코드에는 해당 path 가 존재하지않습니다. router 폴더내의 contants를 확인해주세요.

2024-03-28 04:50 UTC, sungyuha commented on src/router/index.tsx
> +      },
feature-#7 말고, feature-#11로 수정하고 있습니다. 이점 양해부탁드리며, 수정 후 최종 플리퀘 후 pull request 하겠습니다.

2024-03-28 04:50 UTC, sungyuha commented on src/pages/verification/UploadBath.tsx
> +`;
feature-https://github.com/diary-dog/meong-side-FE/issues/7 말고, feature-#11로 수정하고 있습니다. 이점 양해부탁드리며, 수정 후 최종 플리퀘 후 pull request 하겠습니다.

2024-03-28 04:51 UTC, sungyuha commented on src/pages/verification/Modal.tsx
feature-#11로 수정하고 있습니다. 이점 양해부탁드리며, 컴포넌트 폴더로 구분하겠습니다.
수정 후 최종 플리퀘 후 pull request 하겠습니다.

2024-03-28 05:59 UTC, closed without merging